apiVersion : apps/v1
kind: Deployment
metadata:
  name: "cicdakstemp5122201-5849"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "cicdakstemp5122201-5849"
  template:
    metadata:
      labels:
        app: "cicdakstemp5122201-5849"
    spec:
      containers:
        - name: "cicdakstemp5122201-5849"
          image: $IMAGE
          ports:
          - containerPort: 80
