apiVersion: apps/v1
kind: Deployment
metadata:
  name: "webapp01-deployment"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "webapp01"
  template:
    metadata:
      labels:
        app: "webapp01"
    spec:
      containers:
        - name: "webapp01"
          image: $IMAGE
          ports:
            - containerPort: 80
      imagePullSecrets:
      - name: $CRSECRET
