on: [push]

env:
  IMAGE_NAME: webapp01

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n 51822acr -g 51822acrbb45-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n 51822acr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n 51822acr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n 51822acr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: 51822acr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t 51822acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }} --label dockerfile-path=Dockerfile
        docker push 51822acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    # - name: Update Image Version
    #   id: imgupd
    #   uses: mikefarah/yq@master
    #   with:
    #     cmd: yq eval '.spec.template.spec.containers[0].image = "51822acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}"' -i manifests/deployment.yml

    # # https://github.com/marketplace/actions/replace-action?version=v2
    # - name: Replace Action
    #   uses: datamonsters/replace-action@v2
    #   with:
    #     files: 'manifests/deployment.yml'
    #     replacements: '.spec.template.spec.containers[0].image = "51822acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}"'

    # # Reference: 
    # https://github.community/t/github-actions-sed-usage/185904
    # https://www.geeksforgeeks.org/sed-command-in-linux-unix-with-examples/
    # https://stackoverflow.com/questions/66724889/github-actions-substitute-string-before-deploying        
    - name: Change deployment.yml file
      run: |
        sed -i -e 's/$IMAGE/${{ env.IMAGE_NAME }}:${{ github.run_number }}/g' manifests/deployment.yml
     #   sed -i -e 's/$IMAGE//51822acr.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.run_number }}//g' manifests/deployment.yml


    # - uses: azure/k8s-set-context@v1
    #   id: login
    #   with:
    #      kubeconfig: ${{ secrets.aks_cicdakstemp5122201_kubeConfig }}
    
    # - name: Create namespace
    #   run: |
    #     namespacePresent=`kubectl get namespace | grep cicd-aks-temp-5-12-22-01aaa5 | wc -l`
    #     if [ $namespacePresent -eq 0 ]
    #     then
    #         echo `kubectl create namespace cicd-aks-temp-5-12-22-01aaa5`
    #     fi

    # - uses: azure/k8s-create-secret@v1
    #   with:
    #     namespace: cicd-aks-temp-5-12-22-01aaa5
    #     container-registry-url: 51822acr.azurecr.io
    #     container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
    #     container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
    #     secret-name: cicdakstemp5dockerauth
       
    # - uses: azure/k8s-deploy@v1.2
    #   with:
    #     namespace: cicd-aks-temp-5-12-22-01aaa5
    #     manifests: |
    #       manifests/deployment.yml
    #       manifests/service.yml
    #     images: |
    #       51822acr.azurecr.io/cicdakstemp5122201:${{ github.sha }}
    #     imagepullsecrets: |
    #       cicdakstemp5dockerauth   
